SistemaTCC\Model\Etapa:
    type: entity
    table: etapa
    indexes:
        fk_etapa_semestre1_idx:
            columns:
                - semestre_id
        fk_etapa_etapa_tipo1_idx:
            columns:
                - etapa_tipo_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        dataInicio:
            type: datetime
            nullable: false
            column: data_inicio
        dataFim:
            type: datetime
            nullable: false
            column: data_fim
        peso:
            type: integer
            nullable: false
            options:
                unsigned: false
        ordem:
            type: integer
            nullable: false
            options:
                unsigned: false
        enviarEmailAdministrador:
            type: boolean
            nullable: false
            column: enviar_email_administrador
        enviarEmailBanca:
            type: boolean
            nullable: false
            column: enviar_email_banca
        enviarEmailOrientador:
            type: boolean
            nullable: false
            column: enviar_email_orientador
    manyToOne:
        etapaTipo:
            targetEntity: SistemaTCC\Model\EtapaTipo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                etapa_tipo_id:
                    referencedColumnName: id
            orphanRemoval: false
        semestre:
            targetEntity: SistemaTCC\Model\Semestre
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                semestre_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
